### ISSUE TITLE
Switch to Myth

### ISSUE THREAD

**Issue by anthonyshort** [segment-boneyard/app-builder#1]
I probably could have just pull requested it, but I'm just leaving this here to remind us.

@ianstormtaylor

**Comment by ianstormtaylor** [comment]
totes. actually i wanna get this via the new builder too, and i wanna make it a middleware that just smartly rebuilds on dev like J-grubes has setup for debugger

cc @juliangruber cuz i cudnt resist calling you j-grubes but then it was at the cost of a cc :(

**Comment by anthonyshort** [comment]
Pure has the font-variant plugin which is slightly annoying because `font-feature-settings` is super buggy across browsers it seems

**Comment by anthonyshort** [comment]
Which is the main reason I want to switch :P

**Comment by ianstormtaylor** [comment]
Pure?

**Comment by anthonyshort** [comment]
rework-pure-css, ya know, your thing haha

**Comment by ianstormtaylor** [comment]
oh haha. yeah Myth has that plugin in by default too. i use it lots to get real small caps. doesn't work only in Safari as far as i know

**Comment by anthonyshort** [comment]
Does it do anything different to just `font-variant: small-caps`? it seems the same, unless it renders things differently. Doesn't work in FF either. But `font-variant` seems to work fine in all of em.

**Comment by ianstormtaylor** [comment]
yeah `font-variant: small-caps` is replaced with feature settings. what you want is `font-variant: all-small-caps` thought which lowercases by default too (from the spec, dumb but thats how they did it)

pretty sure it works in firefox though

**Comment by anthonyshort** [comment]
You could probably do;

```
font-variant: small-caps;
text-transform: lowercase;
```

To get the same effect everywhere, because FFS gives me weird rendering:

![screen shot 2014-01-30 at 5 15 35 pm](https://f.cloud.github.com/assets/36125/2047148/42d8002e-8a15-11e3-8d27-927b814f98f4.png)

**Comment by ianstormtaylor** [comment]
yeah but than it will use the janky version of small caps that are just caps scaled down by an unknown amount, no? instead i use this everywhere and it works fine everywhere except safari as far as i know:

``` css
font-variant: all-small-caps;
```

can i use even says safari is supported for some dumb reason :/ http://caniuse.com/#feat=font-feature

**Comment by anthonyshort** [comment]
Nah font-variant: small-caps uses the real small-caps if it's available in the font

**Comment by jonathanong** [comment]
i'm guessing i'm going to be working on this? 

> totes. actually i wanna get this via the new builder too, and i wanna make it a middleware that just smartly rebuilds on dev like J-grubes has setup for debugger

what does this mean? express middleware? do you have a reference repo?

**Comment by juliangruber** [comment]
We have a koa middleware that rebuilds on requests to html resources in dev, and relies on makefiles for prod

**Comment by ianstormtaylor** [comment]
actually @yields came up with what i think is a nicer solution to keep the logic in one place. in dev we just do:

``` js
app.use(function(req, res, next){
  exec('make', next);
});
```

so that we don't end up with diverging build steps, since that gives us nice mtime checking which the regular "build all the time" doesnt
